openapi: 3.0.3
info:
  title: Percentage API
  version: 1.0.0
#servers:
#  - url: http://localhost:8080
paths:
  /api/v1/calc:
    post:
      operationId: calculate
      summary: Sum two numbers and apply an external %
      tags:
        - Calculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalcRequest'
      responses:
        "200":
          description: Successful calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalcResponse'
        "503":
          description: Percentage unavailable
  /api/v1/history:
    get:
      operationId: getHistory
      summary: Get call history (stream)
      tags:
        - History
      parameters:
        - in: query
          name: page
          schema: { type: integer, minimum: 0 }
        - in: query
          name: size
          schema: { type: integer, minimum: 1, maximum: 100 }
      responses:
        "200":
          description: History page
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HistoryDto'
components:
  schemas:
    CalcRequest:
      type: object
      required: [ num1, num2 ]
      properties:
        num1: { type: number, format: double }
        num2: { type: number, format: double }
    CalcResponse:
      type: object
      required: [ result ]
      properties:
        result: { type: number, format: double }
    HistoryDto:
      type: object
      properties:
        id:        { type: integer, format: int64 }
        endpoint:  { type: string }
        params:    { type: string }
        response:  { type: string }
        createdAt: { type: string, format: date-time }
